# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
variables:
    SKIP_TESTS: "true"

include:
    - project: oceanbox/gitlab-ci
      ref: v5.0
      file: NuGet.gitlab-ci.yml
      inputs:
          project-name: oceanbox.geojson
          project-dir: .

dockerize-fornix:
    tags:
        - nix
