variables:
  SDK_VERSION: 9.0
  SKIP_TESTS: "true"

include:
  - project: oceanbox/gitlab-ci
    ref: v4.1
    file: DotnetPackage.gitlab-ci.yml
    inputs:
        project-name: oceanbox.geojson
        project-dir: .